import java.util.*;

public class Advent_07{
    static int MAX_SIZE = 100000;
    static int SIZE_30M = 30000000;
    static int SIZE_70M = 70000000;
    static int totalSumGreaterThan100K = 0;
    static int closestTo30M = 0;
    static int sizeNeededDeleted = 0;
    public static void main(String[] args){
        int max = traverseTree(processInput(getInput()));
        System.out.println("Sum of Dirs Less than 100k: " + totalSumGreaterThan100K);
        totalSumGreaterThan100K =0;
        int freeSpace = SIZE_70M - max;
        System.out.println("Free space: " + freeSpace);
        sizeNeededDeleted = SIZE_30M - freeSpace;
        System.out.println("Free space needed: " + sizeNeededDeleted);
        closestTo30M = Integer.MAX_VALUE;
        System.out.println(traverseTree(processInput(getInput())));
        System.out.println("Smallest Dir to Delete to give 30M free space: " +closestTo30M);
    }

    public static int traverseTree(Dir start){
        int currTotal = 0;

        for(Dir file : start.contents.values()){

            if( file.size == 0) {
                currTotal += traverseTree(file);
            }
            else {currTotal += file.size;}
        }

        if (currTotal <= MAX_SIZE) totalSumGreaterThan100K += currTotal;
        if( currTotal < closestTo30M && currTotal >= sizeNeededDeleted) closestTo30M = currTotal;
        return currTotal;
    }
    
    public static Dir processInput(List<String> list){
        // assumes the first item in list is cd
        Dir start = new Dir(list.get(0).split(" ")[2], null, 0);
        Dir currDir = start;
        for(int i = 1; i < list.size(); i++){
            String line = list.get(i);
            String[] input = line.split(" ");

            switch(input[0]){
                case "$":

                    if(input[1].equals("cd")){

                        if(input[2].equals("..")){
                            currDir = currDir.parent;
                        }
                        else{
                            currDir = currDir.contents.get(input[2]);
                        }
                    }
                    if(input[1].equals("ls")){} // do nothing
                    break;
                case "dir":
                    currDir.contents.put(input[1], new Dir(input[1], currDir, 0));
                    break;
                default:                    
                currDir.contents.put(input[1], new Dir(input[1], currDir, Integer.parseInt(input[0])));
            }
        }
        return start;
    }

    public static List<String> getInput(){
List<String> l = new ArrayList<String>();
l.add("$ cd /");
l.add("$ ls");
l.add("dir brdsppd");
l.add("dir dnjqmzgg");
l.add("126880 fmftdzrp.fwt");
l.add("173625 hhfqgzfj.qvt");
l.add("dir lbbcfjl");
l.add("dir mzdqcb");
l.add("dir npppw");
l.add("dir plmb");
l.add("6337 rfgtcj.tdn");
l.add("dir szfw");
l.add("230140 vmc.cdf");
l.add("$ cd brdsppd");
l.add("$ ls");
l.add("dir gjc");
l.add("dir lcz");
l.add("218543 ndqmcv");
l.add("dir qnj");
l.add("dir rrdd");
l.add("dir zppsglq");
l.add("$ cd gjc");
l.add("$ ls");
l.add("dir bvctghh");
l.add("262132 cbczvmdf");
l.add("111855 dnltsq.fwv");
l.add("22416 fnrwscz.vwb");
l.add("dir gwd");
l.add("dir lsprzlbf");
l.add("$ cd bvctghh");
l.add("$ ls");
l.add("dir lsprzlbf");
l.add("dir lwfgnzz");
l.add("dir tjslbpb");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("182522 hhfqgzfj.qvt");
l.add("dir hts");
l.add("229288 jtpdh");
l.add("dir lwfgnzz");
l.add("284594 szfw");
l.add("89639 tgdsjl");
l.add("$ cd hts");
l.add("$ ls");
l.add("11158 dnltsq.fwv");
l.add("52582 tchv");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("dir tjslbpb");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("58586 jtzmjgw.bql");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("199598 rlhz.pbs");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("119666 fmzfs.glg");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd gwd");
l.add("$ ls");
l.add("dir bcfqd");
l.add("1631 hhfqgzfj.qvt");
l.add("$ cd bcfqd");
l.add("$ ls");
l.add("197168 cqvwnslp.ltw");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("dir jwznh");
l.add("$ cd jwznh");
l.add("$ ls");
l.add("dir lpm");
l.add("dir ncs");
l.add("dir vqprn");
l.add("$ cd lpm");
l.add("$ ls");
l.add("15172 bnw.rqm");
l.add("215818 flpbspn.stt");
l.add("$ cd ..");
l.add("$ cd ncs");
l.add("$ ls");
l.add("dir rzdbw");
l.add("$ cd rzdbw");
l.add("$ ls");
l.add("15150 cvjldjt.gdc");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd vqprn");
l.add("$ ls");
l.add("23882 njjjh");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lcz");
l.add("$ ls");
l.add("37587 gwcvttb.dhc");
l.add("195583 lsprzlbf.vng");
l.add("152648 tchv");
l.add("$ cd ..");
l.add("$ cd qnj");
l.add("$ ls");
l.add("dir bpvl");
l.add("275640 cfvznj.bqc");
l.add("dir lwfgnzz");
l.add("213007 nwbt.mct");
l.add("135231 twpf.pft");
l.add("165501 vmc.cdf");
l.add("88097 vmvs.hnr");
l.add("dir znbdpp");
l.add("$ cd bpvl");
l.add("$ ls");
l.add("dir nmzbpb");
l.add("$ cd nmzbpb");
l.add("$ ls");
l.add("129477 pjlvs.zcp");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("dir lwfgnzz");
l.add("dir rsbdcwjr");
l.add("dir sgh");
l.add("dir wvwmf");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("33186 ftcrfnmd");
l.add("$ cd ..");
l.add("$ cd rsbdcwjr");
l.add("$ ls");
l.add("dir lsprzlbf");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("dir jvcgnbs");
l.add("288445 pjmqm");
l.add("111585 szfw.drf");
l.add("dir vnftvqf");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("dir ctlwjnjz");
l.add("dir lwfgnzz");
l.add("dir tjslbpb");
l.add("$ cd ctlwjnjz");
l.add("$ ls");
l.add("72087 zmhnsmmf");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("151358 sqs");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("112471 mftdzhwj.zvt");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd vnftvqf");
l.add("$ ls");
l.add("120421 lsprzlbf.tqc");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd sgh");
l.add("$ ls");
l.add("228239 szfw.dzv");
l.add("$ cd ..");
l.add("$ cd wvwmf");
l.add("$ ls");
l.add("dir bcjfz");
l.add("$ cd bcjfz");
l.add("$ ls");
l.add("26284 bzhqwdjq.nzn");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd znbdpp");
l.add("$ ls");
l.add("dir szfw");
l.add("$ cd szfw");
l.add("$ ls");
l.add("dir nthzqpws");
l.add("dir snfmt");
l.add("$ cd nthzqpws");
l.add("$ ls");
l.add("96382 twhdbvtw.lbj");
l.add("$ cd ..");
l.add("$ cd snfmt");
l.add("$ ls");
l.add("133360 bjmgtpgh");
l.add("134215 vmc.cdf");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd rrdd");
l.add("$ ls");
l.add("185903 cpgpgntt.tfn");
l.add("$ cd ..");
l.add("$ cd zppsglq");
l.add("$ ls");
l.add("41689 jvcgnbs.hrt");
l.add("169754 wgnpq");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd dnjqmzgg");
l.add("$ ls");
l.add("dir lsprzlbf");
l.add("dir lwfgnzz");
l.add("dir nmvj");
l.add("dir sfpg");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("dir lbw");
l.add("141416 sqs");
l.add("$ cd lbw");
l.add("$ ls");
l.add("48758 cjv");
l.add("235522 dnltsq.fwv");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("36709 bcmtmwcz");
l.add("$ cd ..");
l.add("$ cd nmvj");
l.add("$ ls");
l.add("dir dqpw");
l.add("dir tjslbpb");
l.add("$ cd dqpw");
l.add("$ ls");
l.add("10608 hhfqgzfj.qvt");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("261140 qfzb");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd sfpg");
l.add("$ ls");
l.add("8543 szfw");
l.add("69248 tjslbpb");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lbbcfjl");
l.add("$ ls");
l.add("dir csnjp");
l.add("dir drwpfn");
l.add("301956 hhfqgzfj.qvt");
l.add("dir jvcgnbs");
l.add("dir lsprzlbf");
l.add("dir pdzlnm");
l.add("161886 tchv");
l.add("153858 vmc.cdf");
l.add("87849 wghtg");
l.add("dir zhgchnld");
l.add("$ cd csnjp");
l.add("$ ls");
l.add("dir ffgfmcm");
l.add("dir gtd");
l.add("dir lbjvqv");
l.add("dir lwfgnzz");
l.add("11312 sqs");
l.add("$ cd ffgfmcm");
l.add("$ ls");
l.add("dir bcnvw");
l.add("dir lcf");
l.add("dir lsprzlbf");
l.add("$ cd bcnvw");
l.add("$ ls");
l.add("111692 ftcvs.tcz");
l.add("173665 jpfh.hrs");
l.add("120561 lwfgnzz.zvd");
l.add("dir ngtbzz");
l.add("29479 tchv");
l.add("dir tjslbpb");
l.add("$ cd ngtbzz");
l.add("$ ls");
l.add("dir czrqmh");
l.add("dir jrhpnpw");
l.add("dir lsprzlbf");
l.add("$ cd czrqmh");
l.add("$ ls");
l.add("225055 hhfqgzfj.qvt");
l.add("$ cd ..");
l.add("$ cd jrhpnpw");
l.add("$ ls");
l.add("206497 tjslbpb.zbv");
l.add("$ cd ..");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("66627 szfw.wtd");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("dir cgzlp");
l.add("116060 lsprzlbf");
l.add("dir szfw");
l.add("128885 zht.ptf");
l.add("$ cd cgzlp");
l.add("$ ls");
l.add("18201 sqs");
l.add("$ cd ..");
l.add("$ cd szfw");
l.add("$ ls");
l.add("104128 tchv");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lcf");
l.add("$ ls");
l.add("137662 lwfgnzz");
l.add("$ cd ..");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("151745 fmcgs.tvh");
l.add("37707 gszw.jlm");
l.add("dir lsprzlbf");
l.add("178133 rjw.wrq");
l.add("dir szw");
l.add("267875 tchv");
l.add("198852 vmc.cdf");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("54734 lsprzlbf.hcq");
l.add("81537 lwfgnzz");
l.add("120990 qppfdrf");
l.add("$ cd ..");
l.add("$ cd szw");
l.add("$ ls");
l.add("dir jtvschrd");
l.add("dir zcnpls");
l.add("$ cd jtvschrd");
l.add("$ ls");
l.add("dir gtz");
l.add("$ cd gtz");
l.add("$ ls");
l.add("dir rdzzlm");
l.add("$ cd rdzzlm");
l.add("$ ls");
l.add("55063 tchv");
l.add("8813 zfwvvpvz.zzb");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd zcnpls");
l.add("$ ls");
l.add("282808 dpmd");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd gtd");
l.add("$ ls");
l.add("148653 cmchsg.zdr");
l.add("66537 hhfqgzfj.qvt");
l.add("125493 mdtmqbml.gnt");
l.add("dir rwjdjqcs");
l.add("dir tjslbpb");
l.add("$ cd rwjdjqcs");
l.add("$ ls");
l.add("77026 zpt.gfp");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("dir dfl");
l.add("$ cd dfl");
l.add("$ ls");
l.add("203731 qpsmsjgh.gvs");
l.add("dir tjslbpb");
l.add("84386 vmc.cdf");
l.add("dir zgh");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("dir lwfgnzz");
l.add("140021 qnp");
l.add("312305 svh.vqt");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("49701 lgffdn.gmr");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd zgh");
l.add("$ ls");
l.add("138627 tchv");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lbjvqv");
l.add("$ ls");
l.add("dir bnl");
l.add("$ cd bnl");
l.add("$ ls");
l.add("dir gbv");
l.add("dir lwfgnzz");
l.add("$ cd gbv");
l.add("$ ls");
l.add("dir lsprzlbf");
l.add("36406 lsprzlbf.cfd");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("168615 hlhp.rvp");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("149511 cdpwjbpd");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("232898 dnltsq.fwv");
l.add("181665 hhfqgzfj.qvt");
l.add("62529 qfmhhvvq.prh");
l.add("57822 sqs");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd drwpfn");
l.add("$ ls");
l.add("dir fvgw");
l.add("dir lsprzlbf");
l.add("dir lwfgnzz");
l.add("104745 nqvlqd.mdb");
l.add("203189 qqpmz");
l.add("159549 tchv");
l.add("dir tjslbpb");
l.add("dir wnrns");
l.add("$ cd fvgw");
l.add("$ ls");
l.add("dir tlzmplfl");
l.add("$ cd tlzmplfl");
l.add("$ ls");
l.add("29740 vmc.cdf");
l.add("30062 wgrm.dst");
l.add("181738 zqr");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("dir lcqhctjl");
l.add("dir ldr");
l.add("dir tjslbpb");
l.add("$ cd lcqhctjl");
l.add("$ ls");
l.add("209114 bcfr.gpf");
l.add("$ cd ..");
l.add("$ cd ldr");
l.add("$ ls");
l.add("148649 fzh.pqm");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("241013 dnltsq.fwv");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("288335 cdctnn");
l.add("67277 tchv");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("dir pblzrspg");
l.add("dir qqgddb");
l.add("86103 sqs");
l.add("183539 tjslbpb.wrs");
l.add("$ cd pblzrspg");
l.add("$ ls");
l.add("dir pgl");
l.add("$ cd pgl");
l.add("$ ls");
l.add("305421 lwfgnzz.jdz");
l.add("114244 tjslbpb");
l.add("dir vzff");
l.add("$ cd vzff");
l.add("$ ls");
l.add("80591 rlww.htq");
l.add("86968 sqs");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd qqgddb");
l.add("$ ls");
l.add("dir szfw");
l.add("$ cd szfw");
l.add("$ ls");
l.add("dir jtw");
l.add("$ cd jtw");
l.add("$ ls");
l.add("263 szfw.lzp");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd wnrns");
l.add("$ ls");
l.add("203725 dnltsq.fwv");
l.add("77752 qrg.fnt");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("296356 lwfgnzz.svf");
l.add("294928 ptvdsngf");
l.add("$ cd ..");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("dir lwfgnzz");
l.add("dir tjslbpb");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("105095 tchv");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("53558 hhfqgzfj.qvt");
l.add("189180 szfw");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd pdzlnm");
l.add("$ ls");
l.add("76426 jwttcp.rjj");
l.add("dir lsprzlbf");
l.add("dir qldhzf");
l.add("dir rtdsjf");
l.add("dir sfdtljj");
l.add("69033 slhl.jst");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("71362 vgdr");
l.add("$ cd ..");
l.add("$ cd qldhzf");
l.add("$ ls");
l.add("303106 lsprzlbf.rbq");
l.add("$ cd ..");
l.add("$ cd rtdsjf");
l.add("$ ls");
l.add("45781 pzbgwrdm.lwt");
l.add("dir rzc");
l.add("$ cd rzc");
l.add("$ ls");
l.add("297081 qqvlp");
l.add("86015 zthlr");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd sfdtljj");
l.add("$ ls");
l.add("254377 ftw.fwg");
l.add("dir jvcgnbs");
l.add("153393 lwfgnzz.dws");
l.add("dir pnphc");
l.add("220821 wslttcn");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("92642 bzpvvlsn.gvt");
l.add("$ cd ..");
l.add("$ cd pnphc");
l.add("$ ls");
l.add("288388 lwfgnzz");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd zhgchnld");
l.add("$ ls");
l.add("16588 ftgrpj.srl");
l.add("112044 vmc.cdf");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd mzdqcb");
l.add("$ ls");
l.add("dir bfphcs");
l.add("dir cgjmj");
l.add("dir jgcqqsh");
l.add("dir jvcgnbs");
l.add("dir lccjbtqs");
l.add("dir lwfgnzz");
l.add("dir pprvjm");
l.add("dir szfw");
l.add("dir tjslbpb");
l.add("dir ztc");
l.add("$ cd bfphcs");
l.add("$ ls");
l.add("124148 wzt.qtr");
l.add("$ cd ..");
l.add("$ cd cgjmj");
l.add("$ ls");
l.add("28095 ddjdbdf");
l.add("dir jvcgnbs");
l.add("169536 sqs");
l.add("dir svbsrj");
l.add("159511 vmc.cdf");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("dir crmsnch");
l.add("dir jvcgnbs");
l.add("$ cd crmsnch");
l.add("$ ls");
l.add("195745 lsprzlbf.prh");
l.add("271424 tjslbpb");
l.add("227054 vmc.cdf");
l.add("$ cd ..");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("294249 vmc.cdf");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd svbsrj");
l.add("$ ls");
l.add("49038 cspzcpqs");
l.add("dir czltsqrg");
l.add("98084 ljhljcw");
l.add("dir ntdjg");
l.add("202570 szfw.lpj");
l.add("$ cd czltsqrg");
l.add("$ ls");
l.add("207690 dnltsq.fwv");
l.add("208745 lnns.hsv");
l.add("40703 rgmjszf.vtd");
l.add("$ cd ..");
l.add("$ cd ntdjg");
l.add("$ ls");
l.add("dir szfw");
l.add("$ cd szfw");
l.add("$ ls");
l.add("284994 qzwptr.ggb");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd jgcqqsh");
l.add("$ ls");
l.add("2462 djfwggvp");
l.add("$ cd ..");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("dir ftjprdj");
l.add("289965 zhlrstpt");
l.add("$ cd ftjprdj");
l.add("$ ls");
l.add("dir wnmhs");
l.add("$ cd wnmhs");
l.add("$ ls");
l.add("dir tjslbpb");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("dir jvcgnbs");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("160761 dnltsq.fwv");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lccjbtqs");
l.add("$ ls");
l.add("dir jjrdbgtg");
l.add("77186 sqs");
l.add("116398 szfw.qjt");
l.add("182665 vmc.cdf");
l.add("248366 vqdjwsh");
l.add("$ cd jjrdbgtg");
l.add("$ ls");
l.add("237358 bdvbjs.sjp");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("dir ggptdvr");
l.add("dir jnb");
l.add("dir lcpmzpr");
l.add("222506 lsprzlbf");
l.add("293605 qbjfqh");
l.add("dir smvwg");
l.add("291643 tchv");
l.add("247095 vwdstb.pdw");
l.add("dir wghpmnm");
l.add("dir wtrbfrj");
l.add("$ cd ggptdvr");
l.add("$ ls");
l.add("184198 vmc.cdf");
l.add("$ cd ..");
l.add("$ cd jnb");
l.add("$ ls");
l.add("296536 dnltsq.fwv");
l.add("91419 jvcgnbs.cvq");
l.add("279635 rwt.wth");
l.add("$ cd ..");
l.add("$ cd lcpmzpr");
l.add("$ ls");
l.add("184769 hhfqgzfj.qvt");
l.add("dir qwqcbdms");
l.add("236533 tjslbpb.bnc");
l.add("162397 vmvctfnw");
l.add("dir wcc");
l.add("$ cd qwqcbdms");
l.add("$ ls");
l.add("232132 jgm.tfm");
l.add("dir jnfmcnfh");
l.add("173727 mwrbndt");
l.add("dir qshphcb");
l.add("dir tjslbpb");
l.add("$ cd jnfmcnfh");
l.add("$ ls");
l.add("dir rngnt");
l.add("$ cd rngnt");
l.add("$ ls");
l.add("236114 hhfqgzfj.qvt");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd qshphcb");
l.add("$ ls");
l.add("78407 lsprzlbf.hpd");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("30200 brbz");
l.add("171368 jvcgnbs.vwl");
l.add("236158 sqs");
l.add("285872 srfwnmb");
l.add("dir znr");
l.add("$ cd znr");
l.add("$ ls");
l.add("108194 hhfqgzfj.qvt");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd wcc");
l.add("$ ls");
l.add("167768 jvcgnbs");
l.add("289640 lgthn.cjn");
l.add("28517 lwfgnzz.chf");
l.add("dir nvgfwn");
l.add("43738 rrg");
l.add("81011 sqs");
l.add("$ cd nvgfwn");
l.add("$ ls");
l.add("270370 hgnv.ssj");
l.add("98235 lwfgnzz.nfv");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd smvwg");
l.add("$ ls");
l.add("dir jvcgnbs");
l.add("77510 tchv");
l.add("dir tgrm");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("287955 bqcnj.zzv");
l.add("119021 bsrtmzd");
l.add("3391 cnngp.mbf");
l.add("68540 qjmb.vjz");
l.add("149062 tchv");
l.add("$ cd ..");
l.add("$ cd tgrm");
l.add("$ ls");
l.add("112315 qzth");
l.add("277566 scqp");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd wghpmnm");
l.add("$ ls");
l.add("dir hpm");
l.add("$ cd hpm");
l.add("$ ls");
l.add("113354 hhfqgzfj.qvt");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd wtrbfrj");
l.add("$ ls");
l.add("dir ggrsgzvv");
l.add("dir mvzzsl");
l.add("dir szfw");
l.add("dir vsqjb");
l.add("$ cd ggrsgzvv");
l.add("$ ls");
l.add("dir dpv");
l.add("dir gqtsmnr");
l.add("dir lsprzlbf");
l.add("dir pcjcm");
l.add("137203 tchv");
l.add("84711 tns.sdh");
l.add("$ cd dpv");
l.add("$ ls");
l.add("233264 dmd");
l.add("dir fzlchpb");
l.add("293097 gwmspnm.qtp");
l.add("100283 jbbnssc.nnv");
l.add("$ cd fzlchpb");
l.add("$ ls");
l.add("150431 pdmzrs.rll");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd gqtsmnr");
l.add("$ ls");
l.add("dir jdml");
l.add("dir jfqtjt");
l.add("dir lwfgnzz");
l.add("dir tjslbpb");
l.add("$ cd jdml");
l.add("$ ls");
l.add("148333 bwm.dnt");
l.add("dir lsprzlbf");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("dir cslvm");
l.add("dir lwfgnzz");
l.add("dir rllt");
l.add("265856 sqs");
l.add("dir szfw");
l.add("56452 tchv");
l.add("$ cd cslvm");
l.add("$ ls");
l.add("266380 vmc.cdf");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("dir tzghdrd");
l.add("$ cd tzghdrd");
l.add("$ ls");
l.add("dir tjslbpb");
l.add("dir vhv");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("dir jvcgnbs");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("18188 sqs");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd vhv");
l.add("$ ls");
l.add("95547 jhhblnn.vzt");
l.add("dir srgh");
l.add("$ cd srgh");
l.add("$ ls");
l.add("299624 lsprzlbf.dnr");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd rllt");
l.add("$ ls");
l.add("dir crpcbl");
l.add("308185 dnltsq.fwv");
l.add("dir szfw");
l.add("$ cd crpcbl");
l.add("$ ls");
l.add("209445 dfds.mzh");
l.add("$ cd ..");
l.add("$ cd szfw");
l.add("$ ls");
l.add("dir lsprzlbf");
l.add("159720 vmc.cdf");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("291090 tzrvpv");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd szfw");
l.add("$ ls");
l.add("113605 fbrtbfjm");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd jfqtjt");
l.add("$ ls");
l.add("119124 hhfqgzfj.qvt");
l.add("251412 jvcgnbs.zfm");
l.add("dir rbv");
l.add("dir tjslbpb");
l.add("142371 tjslbpb.czt");
l.add("65455 vmc.cdf");
l.add("47786 zjmtjsv");
l.add("$ cd rbv");
l.add("$ ls");
l.add("300632 dzssgm.pqn");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("221545 pswrb.bsw");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("34086 wshbr.spm");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("118394 djfwjd.fvl");
l.add("65377 qmgcpdr.qjz");
l.add("146317 tchv");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("195086 clqmgmq.gbw");
l.add("dir cpgjgbdf");
l.add("109787 jmwshtg.snl");
l.add("305108 lsprzlbf");
l.add("dir szfw");
l.add("174614 szfw.qjq");
l.add("105247 vmcf.rsm");
l.add("$ cd cpgjgbdf");
l.add("$ ls");
l.add("dir vzddwsr");
l.add("$ cd vzddwsr");
l.add("$ ls");
l.add("91787 nwgfs");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd szfw");
l.add("$ ls");
l.add("193316 tjslbpb");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd pcjcm");
l.add("$ ls");
l.add("dir lsprzlbf");
l.add("$ cd lsprzlbf");
l.add("$ ls");
l.add("210834 hvrpj.cdc");
l.add("29497 wcnf");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd mvzzsl");
l.add("$ ls");
l.add("dir rnrtf");
l.add("$ cd rnrtf");
l.add("$ ls");
l.add("221025 btwgwrp.ctj");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd szfw");
l.add("$ ls");
l.add("dir jvcgnbs");
l.add("dir szfw");
l.add("31365 tjslbpb");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("250409 lwfgnzz.nvf");
l.add("66638 tchv");
l.add("dir tlms");
l.add("$ cd tlms");
l.add("$ ls");
l.add("84192 lsprzlbf.pcm");
l.add("107549 nwqzqcmw.rls");
l.add("97234 svdqvwcz");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd szfw");
l.add("$ ls");
l.add("45362 zsflqrtc");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd vsqjb");
l.add("$ ls");
l.add("dir vvnzdcbb");
l.add("$ cd vvnzdcbb");
l.add("$ ls");
l.add("144027 tchv");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd pprvjm");
l.add("$ ls");
l.add("dir hvst");
l.add("137237 lwfgnzz.qfp");
l.add("dir szfw");
l.add("$ cd hvst");
l.add("$ ls");
l.add("100531 svmvncf");
l.add("$ cd ..");
l.add("$ cd szfw");
l.add("$ ls");
l.add("233868 hhfqgzfj.qvt");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd szfw");
l.add("$ ls");
l.add("14971 tchv");
l.add("$ cd ..");
l.add("$ cd tjslbpb");
l.add("$ ls");
l.add("283684 lwfgnzz.wzv");
l.add("$ cd ..");
l.add("$ cd ztc");
l.add("$ ls");
l.add("dir bwhfncdm");
l.add("161420 jvcgnbs");
l.add("135102 tchv");
l.add("$ cd bwhfncdm");
l.add("$ ls");
l.add("108615 lwfgnzz.msn");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd npppw");
l.add("$ ls");
l.add("94593 cwdz.tlb");
l.add("258598 jsswljc");
l.add("245674 nmmfzscz");
l.add("$ cd ..");
l.add("$ cd plmb");
l.add("$ ls");
l.add("dir dwnpl");
l.add("dir lwfgnzz");
l.add("$ cd dwnpl");
l.add("$ ls");
l.add("15993 hhfqgzfj.qvt");
l.add("264944 vmc.cdf");
l.add("$ cd ..");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("154801 cnbmh.hsh");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd szfw");
l.add("$ ls");
l.add("173334 lsprzlbf");
l.add("dir lwfgnzz");
l.add("70693 szfw");
l.add("$ cd lwfgnzz");
l.add("$ ls");
l.add("dir jgwzcgd");
l.add("dir qgdcjq");
l.add("dir spwcmrl");
l.add("$ cd jgwzcgd");
l.add("$ ls");
l.add("dir jvcgnbs");
l.add("dir nvtvcf");
l.add("$ cd jvcgnbs");
l.add("$ ls");
l.add("131852 cntlhf.mqq");
l.add("217305 dnltsq.fwv");
l.add("174110 jvcgnbs.njb");
l.add("179602 lwfgnzz.mth");
l.add("dir pzcssdhv");
l.add("dir qcmqmnpn");
l.add("227361 szfw");
l.add("dir wmhhl");
l.add("$ cd pzcssdhv");
l.add("$ ls");
l.add("187518 gjfwbwnv");
l.add("115671 lsprzlbf");
l.add("$ cd ..");
l.add("$ cd qcmqmnpn");
l.add("$ ls");
l.add("197002 dlns");
l.add("40030 mmpp.ggt");
l.add("198158 tchv");
l.add("$ cd ..");
l.add("$ cd wmhhl");
l.add("$ ls");
l.add("168011 hhfqgzfj.qvt");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd nvtvcf");
l.add("$ ls");
l.add("dir rrzjjjhc");
l.add("$ cd rrzjjjhc");
l.add("$ ls");
l.add("33548 sqs");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd ..");
l.add("$ cd qgdcjq");
l.add("$ ls");
l.add("252274 prshd.qdj");
l.add("$ cd ..");
l.add("$ cd spwcmrl");
l.add("$ ls");
l.add("dir lslmr");
l.add("dir szfw");
l.add("135076 tchv");
l.add("265608 vmc.cdf");
l.add("$ cd lslmr");
l.add("$ ls");
l.add("172247 rrvwsbl");
l.add("$ cd ..");
l.add("$ cd szfw");
l.add("$ ls");
l.add("192729 rnq");
return l;
    }
}


final class Dir{
    int size;
    String name;
    Dir parent;
    Dir(String name, Dir parent, int size){ this.size = size; this.name = name; this.parent = parent; contents = new HashMap<String,Dir>();}
    Map<String,Dir> contents;
}
