import java.util.*;
;
public class AdventCode_3{

    public static void main(String[] args){
        System.out.println(getCharInBothHalves(getList()));
        System.out.println(getBadgeIn3(getList()));
    }

    public static int getCharInBothHalves(List<String> list){
        int count = 0;
        for(String s : list){
            char c = getCharInBothHalves(s);
            if(c==String.valueOf(c).toLowerCase().charAt(0)) count -= 96;
            else count -= 38;
            count += c;
        }
        return count;
    }

    public static char getCharInBothHalves(String s){
        String firstHalf = s.substring(0, s.length()/2);
        String secondHalf = s.substring(s.length()/2, s.length());

        Set<Character> set = new HashSet<Character>(100);
        for(char c : firstHalf.toCharArray()){
            set.add(c);
        }

        for(char c : secondHalf.toCharArray()){
            if(set.contains(c)) return c;
        }

        return '0';
    }

    public static int getBadgeIn3(List<String> list){
        int count = 0;
        for(int i = 2; i < list.size(); i+=3){
            Set<Character> set1 = new HashSet<Character>();
            Set<Character> set2 = new HashSet<Character>();
            for(char c : list.get(i-2).toCharArray()) set1.add(c);
            for(char c : list.get(i-1).toCharArray()) set2.add(c);

            for(char c : list.get(i).toCharArray()){
                if(set1.contains(c) && set2.contains(c)){
                    if(c==String.valueOf(c).toLowerCase().charAt(0)) count -= 96;
                    else count -= 38;
                    count += c;
                    break;
                }
            }
        }
        return count;
    }

    public static List<String> getList(){
        List<String> list = new ArrayList<String>();
        list.add("vGFhvGvvSdfwqhqvmCPnlFPnCNPcCFcWcr");
list.add("ZbWZDMgsTHsrNNLJcJnsJl");
list.add("HbBWQgZVZZBzbgZphwjqpmmVfdGmjG");
list.add("vvCJLGnthChvtrvCCnRbTRqRPRBtbTRfPRRl");
list.add("djZSgHNNwjqcdWlbcbfc");
list.add("pFgMSfpMfzMDZFSgSjGJQQnCvMCVLnnJQLGC");
list.add("gVhQWQpcWZVwwHVvFvnnnnDFdL");
list.add("lzbPlztjltztzSjfGcPdTHLTHFCnnHCLndFGGd");
list.add("jsNbzbczclttSlfbqlljRQMJRMMpJwRZhspZgJRM");
list.add("hLJvfGcNDttSGvJtvSSJcqbqFBBWbjQqDrqbjDDjjb");
list.add("lTswlzZdssgFpdPwZpMQnCjngCCjWBQBWWQqng");
list.add("PRZMpzPZTdVZTfJvFvLFRctJcf");
list.add("JHbQtHVHHLLbTJmmZddgdgwhllMNhhhTgg");
list.add("spqpNGDjDPMhCFChMj");
list.add("DBSDDGnpSDsDWqWczcvSqWvsBtJJLLZrRVZLJRbBZNVrBHrV");
list.add("GwGhfhPhpHccvwSwrTsmsCjDmqTfbDqjss");
list.add("tQntQcNRJMFnnVQFFctJqCsRmsTjjbDqDlTqTbWT");
list.add("NZdVBZZNFzMFNNNvGprZcLGPGrrpcP");
list.add("SvCPLrrlCSvZLrCPPBNPRvNLQBbpmbdggQTTfpfQgpgTqbbb");
list.add("HVjHwMVwWtdMGwtwMwdhDFgbJgJqTmFMfFfmmfTTpq");
list.add("whtHVcjDtHWtsWdwVGVHthDPzRrNSsCRLrLRlZNzZSNzNR");
list.add("rjrlCCBtbtntwPPt");
list.add("FvfJHqBJQWWgWgWLwnMwMLbzvhwTTp");
list.add("WqHgWqBFgGfQgHfVdQFfVfrDllSsRSDmVmRCZZmSSSSZ");
list.add("gjnppCgGHNPrqqmFnnbr");
list.add("tGltVlJRtLRlrqcJcqZDqBJc");
list.add("VvhLlvWltWdVltRTLTfgwSjGNHhggQNQNjps");
list.add("HDWjCNfQjmwgWhcwPPVbZGcpMb");
list.add("sFltFBRRSRJBSSsBlSSnRLPZbVGMVPZpMpPZpcMrFZMc");
list.add("BLTBsstlqBRRBSvJJBsHdgdDNHCQHvbdCjQNNW");
list.add("lRGzWLZNFwJVbVVGcJ");
list.add("HqqpjPvHQnJgVgTnbdTV");
list.add("rVvjBQHQrQhCrzlzWrRlDZ");
list.add("jZjTZRSjZnhGZhzGnG");
list.add("HbnPHrCbBDMnhcrVLWWLLWWg");
list.add("MBwbCNDDptwNMttjdSnsqSRSFFdjtj");
list.add("bSfvcsNsDdccHHQm");
list.add("ljrlplvBhDHDHHHHJl");
list.add("jgpzhrzRrvhFRFrzFnWfZtTwSWZPbbqNbsTqsW");
list.add("vvCTvcDzHcgtvWjvcDcvgBCgwTdPFPpwpwmTSwwmdPwZpfZh");
list.add("rNLMNVqLGNrVsRNJNsPnGnnfnpSFGdfddndd");
list.add("VPQsMbVsPbzzvgCzgv");
list.add("wPsrqprHQQZsChZn");
list.add("cjgFLwWDlDltfLmTCnmWCnZZChCQ");
list.add("FccccSLGFwjVlfVLLtgdSPSpMpBMdMBRRdHdBp");
list.add("mQQcpmCCprrfLQqZVGqLGv");
list.add("PtsJdsMtTTTvFqLTnnqbGZ");
list.add("HjldthsHWztJzstZhBcHDDgpNpCpmrpgSD");
list.add("lCmhDljDJgWggcnh");
list.add("LdQrbdTDQGfGLPdqqFrHwRJcWRHgHBWHBJ");
list.add("sLqsGtDqdGQfSTsqtfqqVMzjCzlvllZljNpCsMMl");
list.add("CfLCZCCqqHlhSSrrtpRjpL");
list.add("mWQbnQZVTWwNdwmDSbpbrFptjDrjRj");
list.add("PJWVnTWPVnnclqqBsCCZHP");
list.add("tqvtbNCgqJSgZgZvSncrrcGjBGhcnVcR");
list.add("DswGQQQdRcjBnRDn");
list.add("sMdlFMQQpfZbvlNtZGgN");
list.add("RMlPllHtrlrlcZLsZfLcfwdDGD");
list.add("QppnQhTBgwQDJsGzLQ");
list.add("gTjnmjvphDSNMbtMbtMRHNVr");
list.add("RHHcChrVVChCWQmRnMZmnmbTbGmFnqTT");
list.add("gpzpfpszDwvDDNdwjdstnSMMHGMqvZnFTTZqbq");
list.add("DsDdpfppwHsgJdjzfdDjdssLPlRccPQQrJcchPQWWQRhlQcr");
list.add("rsrjQjnRnQZZqMmMMVqs");
list.add("WTSTdvJLvTGJTGCMGvzBBpVVqqFVzBzVmf");
list.add("tTSJhGLJbJhLJRRbHPQbnHHMrl");
list.add("GGgMgBJHWHhLWMhWhgfrhgWLzmsmlzTtzHmsmlszRtszRVlT");
list.add("bvScppfcQfcQSFCQpnPqwwTdRTvmzVssvswtddsv");
list.add("ZDpqnPbQbPPnQbFbfSPSqbQJhGrjgMZBhWLrLrBBBBJWhg");
list.add("hQCCGCNhDmGFJsTt");
list.add("fcggBBpvBSrtsRTpRmpD");
list.add("wflWlBlfnvfWWgMNPPLhPnzhPmLQ");
list.add("pcGGTvVpcQLLzSPPPpVBVQwngNqgsJqgJgqSngsJMqJg");
list.add("RZDFGhtCDGmWfWsNdwJhnMgwswqJ");
list.add("ZCGjRGjZllFGHvvcTPjPTQpB");
list.add("FDVsWrFZnnnfNRJdgBBBMLsJLH");
list.add("wcThcTphvCThwTlblpzwGlpLRgHJWLgHLBHdHWJLBLWR");
list.add("mwcbPmClwlzlwvvbTmWbQSjZmZSrDnSNVZfVFnZf");
list.add("tMlttlFRSrcSFcwQSRwSzrMMPPGGPGLWgNfTNTcLPNPGBPPG");
list.add("pbZVCDTqnCjVDHnHVnhBPBBbhBhbhgLgmWLh");
list.add("qZCJZJqqjjCVvvRQltlzTrJtMMMw");
list.add("QvvdBDdMbdFFJrMMjjmjCfCntC");
list.add("lHTPsNLPcfVZLnfj");
list.add("GgsWpHPpTPWpNsGvgdnDbQRQFRbdQg");
list.add("jPNwllsVZjhslSjwGShZMdJDmmdmWLtMDDPHMPFd");
list.add("QbvpDrbBrtMbbHJmcH");
list.add("vznvzBRpBprQBqQZjNswwZDnSlGjZl");
list.add("PdNTzLQPLrVMzGcMtt");
list.add("FsSvDrvmrwDggHGwgV");
list.add("vlpZpZmfnmFTlTWJWdbrdh");
list.add("mZmnggMTSJrrmnrbmTbngJMtwPvwzzRvPGhQdGZPGPLvGvRd");
list.add("FFVBNHVlFlDfCsWwLwPzzhGPCvzhQv");
list.add("qBHLsDcfqFfDDfsFLNcNNBFsrgpMpnJSbnmTnrtmbMSqnpnr");
list.add("qjBNwBPNPspqddssbsTsMDhTDrThQb");
list.add("gvzZSZzFbgHnrHmn");
list.add("fcvfZcRSZFGfZcvFbGttcPfpVjWVwqBqdwNdwNNpqV");
list.add("RrTmtTrqznrnRCSqJrWlWDbhWVnfVDVWdclV");
list.add("QBBgHQGvHHQswLHQQLGLHdLhfhlZZFlsscVDZfWfDhVlZZ");
list.add("dLBMPpGPjLHPHPBHjjgQjHQztSJRztmrNCSCmSpmprrrrz");
list.add("HHWJgjjsJrPBWBjgWgDvbbvtbNDNVtttMPPp");
list.add("SnLTlhhNSntRVVLFVbbb");
list.add("ChqdcNTNqqJCrQrQrrBC");
list.add("BvfLLngFLDrrlDFDDnGmGlmzqzdGqMMWWwWW");
list.add("RVsPbsbVZbjctccCcsCSPmdNqMqMWddwqVzhhNHwHd");
list.add("tcsjPZRctZTSbbtSbtsSjZznnJfJBrfJgLvJJDDBvpTrgp");
list.add("LJJsNdtJQtbWRJQttjGhjVnjcnzcsczGqj");
list.add("MDPPlvCwrTlZfMMvTlPTdVcVhVVjchSBrjccSnnq");
list.add("lgZCvTTZfMgHLptdRgmR");
list.add("gCDrJRNgJDZRCwMgqGbtVVjTjlFbbTtR");
list.add("mccnfcnSQScdvdcQQQpWdnWSjPqTbFFlbPqbPVGNjTPjtN");
list.add("NnzmpWmBBzzpzDgwhDghrZrw");
list.add("wcbVDBQwVBFQLFQDQcqQcLcJfpHJjmljGgMHfcfgGgjf");
list.add("PtnWMtSnlgJmWWmm");
list.add("nThPtRnzntstvrtRPqDFLMLdDwBBFLQDBT");
list.add("zshqnVqTwqHqZQgZDSZjpFjFFF");
list.add("PsBRvttdcgFFBSmc");
list.add("GlPsbLtrvrrrtJlCTnVTlwwfnhwVqH");
list.add("CvVVnFwWZnZwJZMNlCMNMpbMrrQG");
list.add("cpghqzqqtzbGMjTNclGN");
list.add("PqLBsgqBsSfBffShVmvRVwWsFpwZVpsn");
list.add("LzsLSScvscqNdGdgddQjCDbzhpCDbRbhDpDDwDwt");
list.add("ZlMBBBnlMFVFHVMJflJjJBfhRnCbCDpRttRPDCbWpCRbpW");
list.add("mlrFmJrmscNGmsjm");
list.add("FqQjLRjfvTFvlPHHNPMBDDNDPR");
list.add("chWptpcWTzBPMsMMMBHW");
list.add("zcJghwJZpZcgnctccdzzpGQrbQbblFFlTCCFTbdCFCFq");
list.add("QcwNpCcQzpwtCGPPPnrGrfHfvN");
list.add("FgjhhhjMVFVjqRRqDBVBqvMZvdrHnPZWZvsnZHdWnv");
list.add("ShBFhDVghhTBgBBFRRgRCmCPCcpPbwCmLTcCmbpb");
list.add("ZzlzsBzZnWnsBhFRvfvvLfWqfvMv");
list.add("GgQGjjddHHPwpHpTGjPdHMvtvwJqLtJRFlRFRqMwLc");
list.add("dgbbdjpGGgTHGGgQgdpmpgblrBrhrhCBSSznChsVhBsmNB");
list.add("PhSwPdnpsmSWWcjjDFNqnc");
list.add("GJGCTLbTZTrlfflVLFchHDHHDFcVVN");
list.add("RhlhrllQZhCsPvRBvMtSvw");
list.add("GVgnrgTWGVGjLVjWSpvvNmPTmpQmzvhf");
list.add("tBbBDsFtszzSSbPZbh");
list.add("BqlqdcqSJtFMdMjWrnGCWRrWGG");
list.add("sJVJsQhMhPPSQMwdHRmmsmmwRmsr");
list.add("zLFjLDTBFNWWwrqrffldlRdFRq");
list.add("BLjzjTpzLpzWGTbQpMJvVMQwQhhMQM");
list.add("RqSztDRhJDLmRMLlfvsP");
list.add("dMdMMHZCsnbdvmbP");
list.add("VHcZVVcZTwTQpgHQcgFMFBpDDzBqqqDhqJSjSjJjSD");
list.add("rdMnMGjdHhfnjqWWDJPpGWPtvW");
list.add("PTBSQSSzZSBSCzQFFSlZTFSvcZpWWcJvtJppvZpLLcDVcv");
list.add("sgQCsBmmlFCPFFzTgTBgdNnrNndnMrrrfbrNjf");
list.add("bpZdggTjHbgLglpHjldvHpjdhTVzmhzzzFPzmhFsFQSFnhhN");
list.add("rPCDBcCCMPGcWDNNWQzQQSNQnNzQ");
list.add("fCCJtDtGGGfGBtGqBrrcfRBcvPwpLgdZZvHdljvqpvdwbpvl");
list.add("qpmsNldnlHlCqQlHsHNHwJpJMtwvvvjMvfWjpDtt");
list.add("TccVBScrzBzzTGPbVTPQhWjfMjwwRtJtjMtWDWWfDS");
list.add("FQFbzBGczGBFLnFmmqsCLg");
list.add("qpblblvpvJzStJDrhrnGrdhDfFqf");
list.add("ggNQNwBgmTcgCBTBTQQjNfDCnZRRRrRGCnrFfdnhrC");
list.add("mjVFHQTHNjTwcmpzJzHltltbSssS");
list.add("WChWmdcmzndhFcZrrbvrVMVssj");
list.add("NQLDlDplpSJGpLfRRMZVBBGjVsGbbjbBZsGv");
list.add("QNDfNqlpLgSfNfNgNfpgpqwndwWwnCCnnTFMdHndzn");
list.add("ZGRPTngTZMSGMGnhSgRjQHsPbqjmsWHQCQWbNN");
list.add("BFLLfpzVDBfDdlfQcsbVcNmQsqqbcC");
list.add("zFvdplLDLtzFmrrwMMtTrShZ");
list.add("nTdmnVCGqTsSBTqv");
list.add("HlMPwMlHfPSfBBmFBfSL");
list.add("trHHwRHRwMHPMJQJHnDhbdRhdpCZmChNnd");
list.add("lwHWjzplvHqWHGsMLsLwLfgdfLdg");
list.add("tPJNPQmQmSGcTtFmctGmSCBgsBBRbLBRVdLVLCBBLgVf");
list.add("FPtTPQNPrPPQctTcNPSQJJPDjlzplnGDDjWWplWHhGvpnr");
list.add("jwvvDbvsRsrrjrfvfrrZsPpCpmPJJPqlqWmzRJRTqq");
list.add("HdLttdSQHdLHMMtNdLMSTtHpCmPplWhCzmzmPWlJhlNplP");
list.add("BTSLtLLQtnVZDnffbwfw");
list.add("snvQdrtrQprWpgmGLp");
list.add("FhzwlwHccBcljFBSDmHmLpgRmPDCffWL");
list.add("zFhllqjczzwJqqSqlZMsvJgVNMTbssVNnQbb");
list.add("dLZHrWjWPFZWZnPjZttjddFnMDVMGJMQqvMVGVRVpjVpGVvv");
list.add("zhzTwTlfTwCsShSgNhfzsQQqvMQStQMDGJJGvGQVvq");
list.add("TTwCBfsfBwhzwTBCzlmHZdLmBBbtLnLbFnnF");
list.add("BhBRLFmlBlmhgShHmhSlZlFgvbQNwvcsvMCcsQCwNQvNMsBw");
list.add("ttWddDjrfjDcssscDbvH");
list.add("jfjfPWdzdfjdnWpjtrzqnhmJGJFhSJRHSmSmlqlHmq");
list.add("QvJTgvsvghHRHHNbZvNZTRSzBBCLrDqzrfDDtJSqSLBC");
list.add("cPPwdcFFPDwfFrBrFfFfrC");
list.add("nppwdplpRvllsgDH");
list.add("BGLLWLLwHVZwHnNhwsMsrqMqhh");
list.add("STlTpDpmjzmjjjgccqdsbNbBhlNnNMhsqs");
list.add("pjmgjfSDSzmSgFzRZQfRRZLBVLVtZZ");
list.add("WHjddztMtVLNNFFTmbFPFPRw");
list.add("bJnvpQfqccQJZfpcbvCphcFGDPFGRwDGDDGwGsmPFnPF");
list.add("rvffQJZJqrpZCJZJQrQpvBvStlSWSzVSWBbzBLzjtjWWWj");
list.add("SJFMSMGSDLTsFgHvHL");
list.add("mNzRrRRzjzqqgPHvLTHjlvWg");
list.add("ZLbRpRnRnCrbmnmrRRNnwbGfMwDwfDDdSVMdVJdd");
list.add("nsqTbhcDssPsPWsnchPJMSTSMmJMwTSTCJJfJw");
list.add("DHvFvvdHpvpGFHDMVVJVplCCVpggCl");
list.add("RdQjtvHtDQNGsZqzcqPqbNcq");
list.add("GFzRjczzQJnLjJvvTj");
list.add("mSfHrNHDzHDrDSSSBvTZLTNqWJWBWLlv");
list.add("PfgCmfPzDVrtHsddVMsRFcVFQM");
list.add("sfBgfBfBsHBHFGhsqfjgQZtQQMdZgbZQptbM");
list.add("rNLRSzRTrrvvLSTWGpjpNZdQPtGtMdNM");
list.add("wvSWLwzTGTCcwwwJwvwcrcRcVfFBqhhVhDqhBllBfFqBCDCs");
list.add("LbTpDTcMTSzzMLhScnDnSppNQwVNZFBVnFsrwQQZrQrQrN");
list.add("tJtJCRlGWljGWCtjJZVPsJBsVwQmrQNN");
list.add("fvHRftqjGfWGwtfGqvLTzDTzzzchSbMDTd");
list.add("JJhWZlhqLDHtBDrqrB");
list.add("bwwmfrSmbmFjVSFQwSdpDvGdpPnRvDtHpGtGPG");
list.add("VgFfcSQfFgmLLrNThllTZc");
list.add("QmfvrpnvrrJGnBSCFTBMSWFS");
list.add("NVMggbVPzCTgDFDD");
list.add("NRqHRZjVRZdRVdZwNPrMrchGhGpcGfvhQlHJ");
list.add("nlBdCldndlZTttSSBBccPfGWLLHcTTcWPbbW");
list.add("jpsFzFmzDzNzDGChGcGGmPQHQf");
list.add("CNzqvvVJNFqvgRtlqRtdnwSZ");
list.add("MJtDbNHDDpmVPJVzzjLm");
list.add("RslhvlfRTWvWWRwfllSZngmggznjSPznLjmSnz");
list.add("TlhffRwWQhChDqbBQLFHqNrb");
list.add("HWnmSbzflWltlzLfWWDzjMBvCjjCTCgcMvzBBB");
list.add("qRRRZJwhZFGdRNfghVjMVVgfcghC");
list.add("QFFqwNNNwdNZZpqqZfnDSHmmlDLtWtHWlQmD");
list.add("JrFdNTTLRBTJrFVrBNdVLFBdlHbzQQsQzbPJtpbtltWsHbQw");
list.add("gZffDfMlCfjCSqMcpHPWHszstzHjQwpb");
list.add("GMnvfGlfvSqvcMMDgDDcfnqSVFRdmTmVdNBTdmRmBFVnLLBT");
list.add("ZvRHtDcZntLZssMssQBrMdnC");
list.add("jglqlVdlbqgVWjJMbrrBCpmQBBfrpm");
list.add("GqVVPPjPNjFVllNjJjFDvzTLZRvcLRLvTGdGDv");
list.add("fDVzvVfzzZPMsMbb");
list.add("LHtBwLBdhFgdHLLthRwFGGMsmrHMmmbZSmqbMGGG");
list.add("bblRwbTRlllfVQnCQn");
list.add("fVZzjRzpzpVCRPZhVWQvvLsWWWFQlmjWmG");
list.add("JDHgJdtwbZqJqsWBBDLlQlvLms");
list.add("cHHtdbqwrqbbtSbTgSTcVCMRZnRRVNhVPNMPpfMc");
list.add("fCMPBBdpMpsqMssQccnV");
list.add("TlwGWDjDZHLjZHHlLGmnlnNcRllsJcqtsJRV");
list.add("ZHhZHThLLrGwjDDjLwGWWWSjPpbpzrvBFBFdBBbqvCbpFfpg");
list.add("bvDfDPtCVfFFVdWWpmLRmzWzzdBW");
list.add("jgZTghhjrGrsswrsghHrlgTGzSRmMLwpJMSMzWLLWRzpRRSc");
list.add("lpjTpGHlpsNGTHllHrCFnDNPtVnvfQtQtQNP");
list.add("BwlQcwZBwwwQNqJTrrsRGCDTNt");
list.add("bMpVPSfRvCbCtTqsCs");
list.add("dPSRfRpPPjjmLMgZBZBLZZwFQnZn");
list.add("TsVfggTqVnsLVTdTpmDdRhwPRtPRDRwD");
list.add("ljHBSWZvvFWvBFPppnQPwnpmzR");
list.add("MSHSjbBclBSjccLJgqgnLVqTbsTT");
list.add("zncfVgRzVJgnTfVqNHvZJZNJNMpHbdvH");
list.add("PCBpsLjPPmMGdHNdHBHZ");
list.add("jSLlrhLPDWLrPrDCLPCfnpzcVRFcRTnlVncntT");
list.add("ccvSgjHtRjcjSvjvSrBjzSHHwnJPbgwPPZVVVZnPpZlpwnlT");
list.add("ffqNqGGsGWqLTNqZwdndPnnJJpZVJW");
list.add("sNmqhsCMQsMTmjrcmrHrRj");
list.add("gWWWzNVJDwDzVWVDGbGNnhTnHLsmhmhfsQTNSmHd");
list.add("vtMPZvrZvqtqBHljrqSnnmTfLfdnQsjhjmhL");
list.add("MMPZPBqZCrBtvZcrBlDbGbbbzHJCbbRwgwDz");
list.add("hGSRhsMswhcNNGwhwncMnCqCJNrHJPJJrJtCJdqHJm");
list.add("BgVTzWBdTfCmfCJH");
list.add("dlbVFvvWVZhSRQDMnlhc");
list.add("WfpzBZmgJlQVGvWF");
list.add("wHSbrHwmccnrmrHsClGqFGbQjQjjQJQQGv");
list.add("SHPwwsRcrrNtrNSsphmZLzpfzhghZPdD");
list.add("DFDPRpmgbPQtmgBBQDDNJTMMBZsqsZGqGZTGCGSqWG");
list.add("fVvVVLcJVzlvzhqfSTCsZsMGMHqq");
list.add("zJdrrdnzcLlwczwbQmQngRDQPbtDpQ");
list.add("HDZZrpFqwRrQfBqhjjlVlQ");
list.add("czTgvvWPNgPGcTlsQflCVshClC");
list.add("PgNvtSJNvGVMMzNzgGvPGGLHFDdFdmZSZRdDdRrmpFwL");
list.add("SVHNVFVPBHJqHhgFCgzLmCwppm");
list.add("DvDdsGZljDlfdZnjnnZGMzLpRgLfMCLmzfPLhmgp");
list.add("jZDZlrvrZTrTrTQrDsjslHNJqtWbWHbqbPBWNVQWBJ");
list.add("NmGGBdWWJDJTTZHm");
list.add("hFVhcqFjncpcppSjqfppqDvzDDDbbDZvDZZbHfJgvJ");
list.add("jrPqnnHnqSPwPGWPdWst");
list.add("BfhbwMwbbPbHPPPlrdJjrlMJLrJVTd");
list.add("pnQnGnWDjnJdlJCh");
list.add("qshsWvpttzNNQDtzRRPvwfcPHBBBHwbw");
list.add("SHzGRQjhwwhGzjjwRjfBqpqbNCqNnnqqQqPlQC");
list.add("TZtgLmZgVmgdFgmZtdrbNqnqlNlpblnlrnBd");
list.add("DvgmvvZgmWJJjwHHhJSzps");
list.add("JjlrlJjPJgDjJjJnDRDjNwGGqMvSddvPvwQddqSVvq");
list.add("SLpphFLhFZhWLzvswwWqsqVVQWdv");
list.add("FSHtTLZpfzRDDrJgRNjT");
list.add("wjCMvrMlqqWHvWqddrHqgnBNhcffthhVLtpgLBnw");
list.add("GbQFZzZZphnpgNZV");
list.add("FhFzRTDRPzsRQGQGTFlllrJHjdsJlHMqjjHr");
list.add("LqDcTbmJcqSJSTmnrTcmJrfffplfjZsGZfGGZfQLdplj");
list.add("hWddgBvzWFZfPsQlGh");
list.add("RBWBRCdHtgHttVVzHBVNNNDwSTDcSSSbScDDwbwbnmRS");
list.add("FFPzwlZVVrzFFlFLVlllZdHCHPQMnJQQbhhChdhCbb");
list.add("BRRqGBgRfqvgvBDDDTRgghNCMMTQNNbVJMNJJdbbdT");
list.add("DfpgjGfsRWrFVzwLcs");
list.add("PMTSdSmFjhFpNTqvppvRBrRBrDqB");
list.add("HnZZznJbzGZGlZtZWHlJGcGcwMvQBsrwRDQvcDgrgDgrqRvq");
list.add("HGlGfnJZfMMCfNhm");
list.add("nRssqlqVRppVwdMMQwFgtRFz");
list.add("smTvLLTvvNLtwMMQNg");
list.add("CmPGBvZGWvBSGGDmTZjZlhpJcpHDJsbDnlrrprpl");
list.add("djcQGNQqdGdGqMCgndwgCLDMgW");
list.add("nvBvHpBppnvPPnJTBWLJVMwVfWJfCbfWgW");
list.add("hsHHpBsvRTHpsPszTBTTsRTslGqGqlcqlScnqmhZmmZSZSjl");
list.add("DddBHCmfWCBTDBHTHfMpzhzpJJMJsFrGrz");
list.add("tPVPmbnttjPnZvSvSbnmZPZPNpNGMpJNzzNrGJpvhsshMpFs");
list.add("mwnZcbmmStbVtVjbZVlcLTBlcLCRHRDWCWWW");
return list;
}
}
